function exportfigure(outputdir, filename, fig)
% exportfigure(filename, fig)
% 
% Export figure handle fig as a tikz-figure to filename.

switch nargin
    case 2
        fig = gcf;
        floatFormat = '%.15g';
    case 3
        floatFormat = '%.15g';
end

extraCode = {...
    '\\usepackage{siunitx}',...
    '\\newlength\\figureheight',...
    '\\newlength\\figurewidth',...
    '\\setlength\\figureheight{4cm}', ...
    '\\setlength\\figurewidth{11cm}'};

% Crop data to whats visible
% hline = findobj(fig, 'type', 'line');
% hax = findobj(fig, 'type', 'axes');
% xlim = get(hax, 'XLim');

% x = get(hline, 'XData');
% y = get(hline, 'YData');

% idlim = x>=xlim(1) & x<=xlim(2);
% set(hline, 'XData', x(idlim));
% set(hline, 'YData', y(idlim));

fn = fullfile(outputdir, filename);
matlab2tikz('filename', fn,...
    'figurehandle', fig,...
    'height', '\figureheight',...
    'width', '\figurewidth',...
    'extraCode', extraCode,...
    'standalone', true,...
    'showInfo', false,...
    'floatFormat', floatFormat,...
    'checkForUpdates', false,...
    'parseStrings', false,...
    'relativePngPath', '.');
end
