function exportfigure(filename, fig)
% exportfigure(filename, fig)
% 
% Export figure handle fig as a tikz-figure to filename.
extraCode = {...
    '\\usepackage{siunitx}',...
    '\\newlength\\figureheight',...
    '\\newlength\\figurewidth',...
    '\\setlength\\figureheight{4cm}', ...
    '\\setlength\\figurewidth{11cm}'};

% Crop data to whats visible
% hline = findobj(fig, 'type', 'line');
% hax = findobj(fig, 'type', 'axes');
% xlim = get(hax, 'XLim');

% x = get(hline, 'XData');
% y = get(hline, 'YData');

% idlim = x>=xlim(1) & x<=xlim(2);
% set(hline, 'XData', x(idlim));
% set(hline, 'YData', y(idlim));

matlab2tikz('filename', filename,...
    'figurehandle', fig,...
    'height', '\figureheight',...
    'width', '\figurewidth',...
    'extraCode', extraCode,...
    'standalone', true,...
    'showInfo', false,...
    'floatFormat', '%.8g',...
    'checkForUpdates', false,...
    'parseStrings', false);
end
